- name: Install development packages
  apt:
    name:
      - jq
      - make
      - php-cli
      - zip
      - unzip
      - python3-pip
      - pipx
      - sqlite3
      - gh

- name: Install git-squash-merge
  copy:
    src: git-squash-merge
    dest: /usr/local/bin/git-squash-merge
    mode: '0755'
